const processUrl = "./data/process-steps.json";

const state = {
  config: window.APP_CONFIG || {},
  definition: null,
  currentStepIndex: 0,
  truckIndex: null,
  truckPosition: null,
  celebrationPlayed: false,
  isEventFeedOpen: false,
  fields: {},
  answers: {},
  feedback: {},
  events: [],
  generated: {},
  submission: {
    status: "idle",
    message: ""
  }
};

const appElements = {
  progressBar: document.getElementById("progress-bar"),
  playPanel: document.getElementById("play-panel"),
  stepTemplate: document.getElementById("step-template"),
  summaryTemplate: document.getElementById("summary-template")
};

document.addEventListener("DOMContentLoaded", init);

async function init() {
  try {
    const response = await fetch(processUrl, { cache: "no-store" });
    if (!response.ok) {
      throw new Error("Unable to load process steps.");
    }

    state.definition = await response.json();
    render();
  } catch (error) {
    renderFatalState(error instanceof Error ? error.message : "Application failed to load.");
  }
}

function render() {
  renderProgressBar();

  if (!state.definition) {
    return;
  }

  const isComplete = state.currentStepIndex >= state.definition.steps.length;
  if (isComplete) {
    renderSummary();
    return;
  }

  const step = state.definition.steps[state.currentStepIndex];
  ensureAutoGenerated(step);
  renderStep(step, state.currentStepIndex);
}

function renderProgressBar() {
  if (!appElements.progressBar) {
    return;
  }

  const definition = state.definition;
  const isComplete = definition && state.currentStepIndex >= definition.steps.length;
  const steps = definition ? definition.steps : [];

  // score stats
  const stepsWithQuiz = steps.filter((s) => s.quiz);
  const answeredCount = stepsWithQuiz.filter((s) => Array.isArray(state.answers[s.id]) && state.answers[s.id].length > 0).length;
  const correctCount = stepsWithQuiz.reduce((n, s) => {
    return n + (isAnswerCorrect(s, state.answers[s.id]) ? 1 : 0);
  }, 0);
  const mistakeCount = answeredCount - correctCount;
  const scorePct = answeredCount > 0 ? Math.round((correctCount / answeredCount) * 100) : null;

  const structure = ensureProgressBarStructure(steps);
  const stepsWrap = structure.stepsWrap;
  const stepNodes = structure.stepNodes;
  const connectorNodes = structure.connectorNodes;
  const truck = structure.truck;

  steps.forEach((step, index) => {
    const isDone = index < state.currentStepIndex || isComplete;
    const isActive = !isComplete && index === state.currentStepIndex;

    stepNodes[index].classList.toggle("pb-step--done", isDone);
    stepNodes[index].classList.toggle("pb-step--active", isActive);
    connectorNodes[index]?.classList.toggle("pb-connector--done", isDone);
  });

  if (structure.scoreEl) {
    structure.scoreEl.hidden = scorePct === null;
    structure.scoreEl.querySelector("strong").textContent = scorePct === null ? "" : `${scorePct}%`;
  }

  if (structure.mistakeEl) {
    structure.mistakeEl.hidden = mistakeCount === 0;
    const valueNode = structure.mistakeEl.querySelector("strong");
    if (valueNode) {
      valueNode.textContent = String(mistakeCount);
    }
  }

  if (structure.restartBtn) {
    structure.restartBtn.hidden = isComplete;
  }

  renderProgressTruck(truck, stepsWrap, stepNodes, isComplete);
}

function ensureProgressBarStructure(steps) {
  const existingStepsWrap = appElements.progressBar.querySelector(".pb-steps");
  const existingStepNodes = existingStepsWrap ? [...existingStepsWrap.querySelectorAll(".pb-step")] : [];
  const existingTruck = appElements.progressBar.querySelector("[data-role='pb-truck']");

  if (existingStepsWrap && existingStepNodes.length === steps.length && existingTruck) {
    return {
      stepsWrap: existingStepsWrap,
      stepNodes: existingStepNodes,
      connectorNodes: [...existingStepsWrap.querySelectorAll(".pb-connector")],
      scoreEl: appElements.progressBar.querySelector("[data-role='pb-score']"),
      mistakeEl: appElements.progressBar.querySelector("[data-role='pb-mistakes']"),
      restartBtn: appElements.progressBar.querySelector("[data-role='pb-restart']"),
      truck: existingTruck
    };
  }

  appElements.progressBar.replaceChildren();

  const stepsWrap = document.createElement("div");
  stepsWrap.className = "pb-steps";

  const stepNodes = [];
  const connectorNodes = [];

  steps.forEach((step, index) => {
    const node = document.createElement("div");
    node.className = "pb-step";
    node.setAttribute("aria-label", `Step ${index + 1}: ${step.name}`);

    const iconWrap = document.createElement("div");
    iconWrap.className = "pb-step__icon";
    iconWrap.innerHTML = `<img src="./assets/icons/${escapeHtml(step.illustration)}.svg" alt="" aria-hidden="true" />`;

    const label = document.createElement("span");
    label.className = "pb-step__label";
    label.textContent = step.activity || step.name;

    node.append(iconWrap, label);
    stepNodes.push(node);

    if (index < steps.length - 1) {
      const connector = document.createElement("div");
      connector.className = "pb-connector";
      connectorNodes.push(connector);
      stepsWrap.append(node, connector);
    } else {
      stepsWrap.append(node);
    }
  });

  const meta = document.createElement("div");
  meta.className = "pb-meta";

  const scoreEl = document.createElement("div");
  scoreEl.className = "pb-stat pb-stat--score";
  scoreEl.dataset.role = "pb-score";
  scoreEl.innerHTML = `<span>Score</span><strong></strong>`;
  meta.append(scoreEl);

  const mistakeEl = document.createElement("div");
  mistakeEl.className = "pb-stat pb-stat--mistakes";
  mistakeEl.dataset.role = "pb-mistakes";
  mistakeEl.innerHTML = `<span>Mistakes</span><strong></strong>`;
  meta.append(mistakeEl);

  const restartBtn = document.createElement("button");
  restartBtn.className = "button button--primary pb-restart";
  restartBtn.dataset.role = "pb-restart";
  restartBtn.type = "button";
  restartBtn.textContent = "Restart";
  restartBtn.addEventListener("click", restartJourney);
  meta.append(restartBtn);

  const truck = document.createElement("div");
  truck.className = "pb-truck";
  truck.dataset.role = "pb-truck";
  truck.setAttribute("aria-hidden", "true");
  truck.innerHTML = '<img src="./assets/icons/truck.svg" alt="" />';

  appElements.progressBar.append(stepsWrap, meta, truck);

  return {
    stepsWrap,
    stepNodes,
    connectorNodes,
    scoreEl,
    mistakeEl,
    restartBtn,
    truck
  };
}

function renderProgressTruck(truck, stepsWrap, stepNodes, isComplete) {
  if (!window.matchMedia("(min-width: 960px)").matches || stepNodes.length === 0) {
    truck.hidden = true;
    state.truckIndex = isComplete ? Math.max(stepNodes.length - 1, 0) : state.currentStepIndex;
    state.truckPosition = null;
    return;
  }

  const currentIndex = isComplete ? Math.max(stepNodes.length - 1, 0) : state.currentStepIndex;

  if (isComplete || currentIndex === 0) {
    truck.hidden = true;
    state.truckIndex = currentIndex;
    state.truckPosition = null;
    return;
  }

  truck.hidden = false;

  const targetStep = stepNodes[currentIndex];
  if (!targetStep) {
    return;
  }

  const laneY = calculateTruckLaneY(stepNodes[0], appElements.progressBar);
  const to = calculateTruckPosition(targetStep, appElements.progressBar, laneY);
  const hasPreviousPosition = state.truckIndex !== null && Number.isFinite(state.truckPosition?.x);

  truck.style.top = `${laneY}px`;

  if (!hasPreviousPosition) {
    truck.style.transform = `translateX(${to.x}px)`;
    state.truckIndex = currentIndex;
    state.truckPosition = { x: to.x, y: laneY };
    return;
  }

  const previous = getTruckPosition(truck) || state.truckPosition || to;
  const fromX = Number.isFinite(previous.x) ? previous.x : to.x;
  truck.style.transform = `translateX(${fromX}px)`;
  truck.getBoundingClientRect();

  requestAnimationFrame(() => {
    truck.style.transform = `translateX(${to.x}px)`;
  });

  state.truckIndex = currentIndex;
  state.truckPosition = { x: to.x, y: laneY };
}

function calculateTruckPosition(stepNode, containerNode, fixedY) {
  const icon = stepNode.querySelector(".pb-step__icon");
  if (!icon || !(containerNode instanceof HTMLElement)) {
    return { x: 0, y: 0 };
  }

  const truckMarginX = 8;
  const iconRect = icon.getBoundingClientRect();
  const containerRect = containerNode.getBoundingClientRect();
  const fallbackY = iconRect.top - containerRect.top + 6;

  return {
    x: iconRect.right - containerRect.left + truckMarginX,
    y: Number.isFinite(fixedY) ? fixedY : fallbackY
  };
}

function calculateTruckLaneY(referenceStepNode, containerNode) {
  const icon = referenceStepNode?.querySelector(".pb-step__icon");
  if (!icon || !(containerNode instanceof HTMLElement)) {
    return 0;
  }

  const iconRect = icon.getBoundingClientRect();
  const containerRect = containerNode.getBoundingClientRect();
  return iconRect.top - containerRect.top + 6;
}

function getTruckPosition(truckNode) {
  const transform = window.getComputedStyle(truckNode).transform;
  if (!transform || transform === "none") {
    return null;
  }

  const matrix = new DOMMatrixReadOnly(transform);
  return { x: matrix.m41, y: matrix.m42 };
}

function renderStep(step, index) {
  const fragment = appElements.stepTemplate.content.cloneNode(true);
  const root = firstElement(fragment, ".step-card");
  const eventsCard = firstElement(fragment, ".events-card");
  const form = firstElement(fragment, '[data-role="step-form"]');
  const eventToggle = firstElement(fragment, '[data-role="event-toggle"]');
  const eventContent = firstElement(fragment, '[data-role="event-content"]');

  setText(fragment, '[data-role="step-position"]', `Step ${index + 1} of ${state.definition.steps.length}`);
  setText(fragment, '[data-role="step-title"]', step.name);
  setText(fragment, '[data-role="state-transition"]', `${step.beginState} → ${step.endState}`);
  setText(fragment, '[data-role="step-description"]', step.description);
  setText(fragment, '[data-role="performed-by"]', step.performedBy);
  setText(fragment, '[data-role="activity"]', step.activity);

  const stepIcon = firstElement(fragment, '[data-role="step-icon"]');
  stepIcon.innerHTML = `<img src="./assets/icons/${escapeHtml(step.illustration)}.svg" alt="" aria-hidden="true" />`;

  populateFields(fragment, step.fields || []);
  populateQuiz(fragment, step);
  populateAutoOutput(fragment, step);
  populateEventPane(fragment, step);

  eventContent.hidden = !state.isEventFeedOpen;
  eventToggle.setAttribute("aria-expanded", String(state.isEventFeedOpen));
  eventToggle.textContent = state.isEventFeedOpen ? "Hide" : "Show";

  eventToggle.addEventListener("click", () => {
    state.isEventFeedOpen = !state.isEventFeedOpen;
    eventContent.hidden = !state.isEventFeedOpen;
    eventToggle.setAttribute("aria-expanded", String(state.isEventFeedOpen));
    eventToggle.textContent = state.isEventFeedOpen ? "Hide" : "Show";
  });

  form.addEventListener("submit", (event) => {
    event.preventDefault();
    handleStepSubmit(step, index, root);
  });

  root.classList.add("step-card--enter");
  eventsCard.classList.add("events-card--enter");
  appElements.playPanel.replaceChildren(root, eventsCard);

  requestAnimationFrame(() => {
    root.classList.add("step-card--enter-active");
    eventsCard.classList.add("events-card--enter-active");
  });
}

function populateFields(fragment, fields) {
  const fieldsRoot = firstElement(fragment, '[data-role="fields"]');
  fieldsRoot.replaceChildren();

  fields.forEach((field) => {
    const wrapper = document.createElement("div");
    wrapper.className = "field";

    const label = document.createElement("label");
    label.setAttribute("for", field.id);
    label.textContent = field.label;

    const input = document.createElement("input");
    input.id = field.id;
    input.name = field.id;
    input.type = field.type;
    input.placeholder = field.placeholder || "";
    input.required = Boolean(field.required);
    input.autocomplete = autocompleteForField(field.id);
    input.value = state.fields[field.id] || "";
    input.addEventListener("input", (event) => {
      const target = event.target;
      state.fields[field.id] = typeof target.value === "string" ? target.value : "";
      input.classList.remove("field-input--invalid");
      input.removeAttribute("aria-invalid");
    });

    wrapper.append(label, input);

    if (field.hint) {
      const hint = document.createElement("p");
      hint.className = "field__hint";
      hint.textContent = field.hint;
      wrapper.append(hint);
    }

    fieldsRoot.append(wrapper);
  });
}

function populateQuiz(fragment, step) {
  const block = firstElement(fragment, '[data-role="quiz-block"]');
  const feedback = firstElement(fragment, '[data-role="quiz-feedback"]');
  const feedbackText = state.feedback[step.id] || "";
  feedback.textContent = feedbackText;
  feedback.hidden = !feedbackText;
  feedback.className = "feedback";

  if (!step.quiz) {
    block.hidden = true;
    return;
  }

  block.hidden = false;
  setText(fragment, '[data-role="quiz-question"]', step.quiz.question);

  const choiceList = firstElement(fragment, '[data-role="quiz-choices"]');
  choiceList.replaceChildren();

  step.quiz.choices.forEach((choice) => {
    const choiceId = `${step.id}-${choice.id}`;
    const label = document.createElement("label");
    label.className = "choice";
    label.setAttribute("for", choiceId);

    const input = document.createElement("input");
    input.id = choiceId;
    input.name = `${step.id}-answer`;
    input.type = step.quiz.selectionMode === "multiple" ? "checkbox" : "radio";
    input.value = choice.id;
    input.checked = Array.isArray(state.answers[step.id]) && state.answers[step.id].includes(choice.id);
    input.addEventListener("change", () => {
      if (step.quiz.selectionMode === "multiple") {
        const nextAnswers = new Set(state.answers[step.id] || []);
        if (input.checked) {
          nextAnswers.add(choice.id);
        } else {
          nextAnswers.delete(choice.id);
        }
        state.answers[step.id] = [...nextAnswers];
      } else {
        state.answers[step.id] = [choice.id];
      }
    });

    const copy = document.createElement("div");
    copy.innerHTML = `
      <span class="choice__label">${escapeHtml(choice.label)}</span>
      <span class="choice__copy">${renderChoiceHint(choice.id)}</span>
    `;

    label.append(input, copy);
    choiceList.append(label);
  });
}

function populateAutoOutput(fragment, step) {
  const block = firstElement(fragment, '[data-role="auto-output"]');
  if (!step.autoGenerate?.weightTons) {
    block.hidden = true;
    return;
  }

  const generated = state.generated[step.id];
  block.hidden = false;
  block.innerHTML = `
    Shared result generated: <strong>${generated.weightTons.toFixed(1)} metric tons</strong><br />
    Weighing reference: <strong>${escapeHtml(generated.reference)}</strong><br />
    Timestamp: <strong>${escapeHtml(formatDateTime(generated.timestamp))}</strong>
  `;
}

function populateEventPane(fragment, step) {
  const currentEvent = firstElement(fragment, '[data-role="current-event"]');
  currentEvent.innerHTML = renderEventCard(step.event, step.id);

  const history = firstElement(fragment, '[data-role="event-history"]');
  history.replaceChildren();

  if (state.events.length === 0) {
    const empty = document.createElement("div");
    empty.className = "event-history__item";
    empty.innerHTML = `
      <p class="event-history__name">No prior events yet</p>
      <p class="event-history__copy">Each completed step adds a trusted event to the shared process timeline.</p>
    `;
    history.append(empty);
    return;
  }

  [...state.events].reverse().forEach((event) => {
    const item = document.createElement("div");
    item.className = "event-history__item";
    item.innerHTML = `
      <p class="event-history__name">${escapeHtml(event.name)}</p>
      <p class="event-history__copy">${escapeHtml(event.summary)}</p>
      <ul class="event-history__list">${event.dataPoints.map((point) => `<li>${escapeHtml(point)}</li>`).join("")}</ul>
    `;
    history.append(item);
  });
}

function handleStepSubmit(step, index, root) {
  const errorNode = firstElement(root, '[data-role="form-error"]');
  errorNode.classList.remove("is-visible");
  errorNode.textContent = "";

  root.querySelectorAll(".field-input--invalid").forEach((node) => {
    node.classList.remove("field-input--invalid");
    node.removeAttribute("aria-invalid");
  });

  const validationError = validateStep(step, root);
  if (validationError) {
    errorNode.textContent = validationError;
    errorNode.classList.add("is-visible");
    return;
  }

  gradeQuiz(step, root);
  syncStepEvent(step);
  state.currentStepIndex = index + 1;

  if (state.currentStepIndex >= state.definition.steps.length) {
    submitToFormspree();
  }

  render();
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function validateStep(step, root) {
  if (step.fields) {
    for (const field of step.fields) {
      const value = (state.fields[field.id] || "").trim();
      if (field.required && !value) {
        markFieldInvalid(root, field.id);
        return `Please complete ${field.label.toLowerCase()} before continuing.`;
      }

      if (field.type === "email" && value && !isValidEmail(value)) {
        markFieldInvalid(root, field.id);
        return "Please enter a valid email address.";
      }

      if (field.id === "containerNumber" && value) {
        const normalized = normalizeContainerNumber(value);
        if (!isValidContainerNumber(normalized)) {
          markFieldInvalid(root, field.id);
          return "The container number control digit is invalid. Enter a valid ISO 6346 number or leave the field empty to skip.";
        }
        state.fields[field.id] = normalized;
      }
    }
  }

  if (step.quiz) {
    const selected = state.answers[step.id] || [];
    if (selected.length === 0) {
      return "Choose an answer to progress to the next step.";
    }
  }

  return "";
}

function gradeQuiz(step, root) {
  if (!step.quiz) {
    return;
  }

  const isCorrect = isAnswerCorrect(step, state.answers[step.id]);

  state.feedback[step.id] = isCorrect ? step.quiz.correctFeedback : step.quiz.incorrectFeedback;

  const feedbackNode = firstElement(root, '[data-role="quiz-feedback"]');
  feedbackNode.textContent = state.feedback[step.id];
  feedbackNode.hidden = false;
  feedbackNode.className = `feedback ${isCorrect ? "is-correct" : "is-incorrect"}`;
}

function syncStepEvent(step) {
  const record = buildCompletedEvent(step);
  const existingIndex = state.events.findIndex((item) => item.stepId === step.id);
  if (existingIndex >= 0) {
    state.events.splice(existingIndex, 1, record);
  } else {
    state.events.push(record);
  }
}

function buildCompletedEvent(step) {
  const dataPoints = [...step.event.dataPoints];

  if (step.id === "start") {
    dataPoints.push(`Name: ${state.fields.name || "unknown"}`);
    dataPoints.push(`Email: ${state.fields.email || "unknown"}`);
  }

  if (step.id === "container-intake") {
    dataPoints.push(
      `Container number: ${state.fields.containerNumber || "Skipped at booth"}`
    );
  }

  if (step.id === "container-weighing") {
    const generated = state.generated[step.id];
    dataPoints.push(`Measured weight: ${generated.weightTons.toFixed(1)} metric tons`);
    dataPoints.push(`Reference: ${generated.reference}`);
  }

  if (step.id === "certificate-purchase") {
    dataPoints.push(`Company: ${state.fields.company || "unknown"}`);
  }

  if (step.quiz) {
    const answers = state.answers[step.id] || [];
    dataPoints.push(`Selected answer: ${answers.join(", ").toUpperCase()}`);
  }

  return {
    stepId: step.id,
    name: step.event.name,
    summary: step.event.summary,
    dataPoints
  };
}

function renderSummary() {
  const fragment = appElements.summaryTemplate.content.cloneNode(true);
  const answers = scoreAnswers();
  const isPerfectScore = answers.total > 0 && answers.correctCount === answers.total;
  const resultTitle = answers.correctCount >= Math.max(3, state.definition.steps.length - 1)
    ? "Container accepted with clear process visibility"
    : "Container accepted, but some process chaos remains"
  ;

  setText(fragment, '[data-role="summary-title"]', resultTitle);
  setText(
    fragment,
    '[data-role="summary-score"]',
    `${answers.correctCount}/${answers.total} decisions aligned`
  );

  const summaryLead = answers.correctCount === answers.total
    ? "Every key event reached the right moment in the flow. That is the PILOTS promise: trusted information that moves with the process."
    : "The shipment still completed, but the quiz shows how easy it is for process visibility to fragment when events are not shared at the right time.";
  setText(fragment, '[data-role="summary-lead"]', summaryLead);

  if (isPerfectScore) {
    const congrats = document.createElement("p");
    congrats.className = "summary-congrats";
    congrats.textContent = "Congratulations! You nailed a perfect score and kept every process handoff aligned.";
    const leadNode = firstElement(fragment, '[data-role="summary-lead"]');
    leadNode.insertAdjacentElement("afterend", congrats);
  }

  const summaryGrid = firstElement(fragment, '[data-role="summary-grid"]');
  summaryGrid.replaceChildren(createCapturedDataTile(answers));

  const submissionStatus = firstElement(fragment, '[data-role="submission-status"]');
  submissionStatus.textContent = state.submission.message || "Preparing booth lead submission...";
  submissionStatus.className = `submission-status ${submissionClassName(state.submission.status)}`.trim();

  const summaryCard = firstElement(fragment, ".summary-card");
  summaryCard.querySelector('[data-action="restart"]').addEventListener("click", restartJourney);
  appElements.playPanel.replaceChildren(summaryCard);

  if (isPerfectScore && !state.celebrationPlayed) {
    state.celebrationPlayed = true;
    requestAnimationFrame(() => launchConfetti(summaryCard));
  }
}

function scoreAnswers() {
  const stepsWithQuiz = state.definition.steps.filter((step) => step.quiz);
  const correctCount = stepsWithQuiz.reduce((count, step) => {
    const isCorrect = isAnswerCorrect(step, state.answers[step.id]);
    return count + (isCorrect ? 1 : 0);
  }, 0);

  return {
    correctCount,
    total: stepsWithQuiz.length
  };
}

async function submitToFormspree() {
  const endpoint = state.config.formspreeEndpoint;
  const payload = buildFormspreePayload();

  if (!endpoint) {
    state.submission = {
      status: "warning",
      message:
        "Lead capture is ready, but Formspree is not configured yet. Add your endpoint in config.js to send submissions from the booth."
    };
    render();
    return;
  }

  state.submission = {
    status: "pending",
    message: "Sending your booth entry to the PILOTS lead form..."
  };
  render();

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(state.config.formspreeHeaders || {})
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      throw new Error("Formspree rejected the submission.");
    }

    state.submission = {
      status: "success",
      message: "Your contact details and game result were submitted successfully. You are in the draw and the PILOTS team can follow up with updates."
    };
  } catch (error) {
    state.submission = {
      status: "warning",
      message:
        "The game finished, but the lead form could not be submitted. Check the Formspree endpoint and allowed origin settings before the booth demo."
    };
  }

  render();
}

function buildFormspreePayload() {
  const generated = state.generated["container-weighing"] || {};
  const score = scoreAnswers();

  return {
    processName: state.definition.process.name,
    visitorName: state.fields.name || "",
    email: state.fields.email || "",
    company: state.fields.company || "",
    containerNumber: state.fields.containerNumber || "",
    measuredWeightTons: generated.weightTons || "",
    weighingReference: generated.reference || "",
    weighingTimestamp: generated.timestamp || "",
    score: `${score.correctCount}/${score.total}`,
    answers: Object.fromEntries(
      Object.entries(state.answers).map(([stepId, answersForStep]) => [stepId, answersForStep.join(",")])
    ),
    processEvents: state.events,
    source: "IPIC 2026 booth game"
  };
}

function ensureAutoGenerated(step) {
  if (!step.autoGenerate?.weightTons || state.generated[step.id]) {
    return;
  }

  const spec = step.autoGenerate.weightTons;
  const factor = 10 ** spec.decimals;
  const rawValue = Math.round((spec.min + Math.random() * (spec.max - spec.min)) * factor) / factor;
  state.generated[step.id] = {
    weightTons: rawValue,
    timestamp: new Date().toISOString(),
    reference: `VGM-${Math.random().toString(36).slice(2, 8).toUpperCase()}`
  };
}

function restartJourney() {
  state.currentStepIndex = 0;
  state.truckIndex = null;
  state.truckPosition = null;
  state.celebrationPlayed = false;
  state.isEventFeedOpen = false;
  state.fields = {};
  state.answers = {};
  state.feedback = {};
  state.events = [];
  state.generated = {};
  state.submission = {
    status: "idle",
    message: ""
  };
  render();
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function computeTruckTop(stepCount, activeIndex) {
  const start = 42;
  const end = Math.max(42, stepCount * 108 - 4);

  if (stepCount <= 1) {
    return start;
  }

  const ratio = Math.min(activeIndex, stepCount - 1) / (stepCount - 1);
  return start + ratio * (end - start);
}

function normalizeContainerNumber(value) {
  return value.replace(/\s+/g, "").toUpperCase();
}

function isValidContainerNumber(value) {
  if (!/^[A-Z]{4}\d{7}$/.test(value)) {
    return false;
  }

  const code = value.slice(0, 10);
  const checkDigit = Number(value[10]);
  return calculateIso6346CheckDigit(code) === checkDigit;
}

function calculateIso6346CheckDigit(code) {
  const letterValues = {
    A: 10,
    B: 12,
    C: 13,
    D: 14,
    E: 15,
    F: 16,
    G: 17,
    H: 18,
    I: 19,
    J: 20,
    K: 21,
    L: 23,
    M: 24,
    N: 25,
    O: 26,
    P: 27,
    Q: 28,
    R: 29,
    S: 30,
    T: 31,
    U: 32,
    V: 34,
    W: 35,
    X: 36,
    Y: 37,
    Z: 38
  };

  const total = code.split("").reduce((sum, character, index) => {
    const value = /\d/.test(character) ? Number(character) : letterValues[character];
    return sum + value * 2 ** index;
  }, 0);
  const remainder = total % 11;
  return remainder % 10;
}

function isValidEmail(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

function markFieldInvalid(root, fieldId) {
  const input = root.querySelector(`[name="${fieldId}"]`);
  if (!(input instanceof HTMLInputElement)) {
    return;
  }

  input.classList.add("field-input--invalid");
  input.setAttribute("aria-invalid", "true");
}

function formatDateTime(value) {
  return new Intl.DateTimeFormat("en-BE", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(value));
}

function autocompleteForField(fieldId) {
  switch (fieldId) {
    case "name":
      return "name";
    case "email":
      return "email";
    case "company":
      return "organization";
    default:
      return "off";
  }
}

function createSummaryPill(label, value) {
  const pill = document.createElement("div");
  pill.className = "summary-pill";
  pill.innerHTML = `<span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong>`;
  return pill;
}

function createCapturedDataTile(answers) {
  const tile = document.createElement("div");
  tile.className = "summary-pill summary-pill--captured";

  const generatedWeight = state.generated["container-weighing"]
    ? `${state.generated["container-weighing"].weightTons.toFixed(1)} metric tons`
    : "Not generated";

  const points = [
    ["Visitor", state.fields.name || "Unknown"],
    ["Email", state.fields.email || "Unknown"],
    ["Company", state.fields.company || "Unknown"],
    ["Container", state.fields.containerNumber || "Skipped"],
    ["Weight", generatedWeight],
    ["Shared events", String(state.events.length)],
    ["Decision score", `${answers.correctCount}/${answers.total}`]
  ];

  const list = points
    .map(([label, value]) => `<li><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></li>`)
    .join("");

  tile.innerHTML = `
    <span>Captured data points</span>
    <ul class="summary-pill__list">${list}</ul>
  `;

  return tile;
}

function renderEventCard(event, stepId) {
  const dynamicPoints = getDynamicEventPreview(stepId);
  return `
    <p class="event-box__name">${escapeHtml(event.name)}</p>
    <p class="event-box__copy">${escapeHtml(event.summary)}</p>
    <ul class="event-box__list">
      ${[...event.dataPoints, ...dynamicPoints].map((point) => `<li>${escapeHtml(point)}</li>`).join("")}
    </ul>
  `;
}

function getDynamicEventPreview(stepId) {
  if (stepId === "start") {
    return [
      `Live value: ${state.fields.name || "Name pending"}`,
      `Live value: ${state.fields.email || "Email pending"}`
    ];
  }

  if (stepId === "container-intake") {
    return [`Live value: ${state.fields.containerNumber || "Container number optional"}`];
  }

  if (stepId === "container-weighing") {
    const generated = state.generated[stepId];
    return generated
      ? [
          `Live value: ${generated.weightTons.toFixed(1)} metric tons`,
          `Reference: ${generated.reference}`
        ]
      : [];
  }

  if (stepId === "certificate-purchase") {
    return [`Live value: ${state.fields.company || "Company pending"}`];
  }

  return [];
}

function renderChoiceHint(choiceId) {
  return `Option ${choiceId.toUpperCase()}`;
}

function submissionClassName(status) {
  if (status === "success") {
    return "submission-status--success";
  }

  if (status === "warning") {
    return "submission-status--warning";
  }

  return "";
}

function renderFatalState(message) {
  const container = document.createElement("article");
  container.className = "card";
  container.innerHTML = `
    <div class="card__header">
      <div>
        <p class="section-label">Application Error</p>
        <h2>Process journey unavailable</h2>
      </div>
    </div>
    <p class="step-card__prompt">${escapeHtml(message)}</p>
  `;
  appElements.playPanel.replaceChildren(container);
}

function renderSketch(type) {
  const sketches = {
    booking: `
      <svg viewBox="0 0 320 150" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
        <path d="M28 113H292" stroke="#163242" stroke-opacity="0.18" stroke-width="4" stroke-linecap="round"/>
        <rect x="40" y="42" width="92" height="54" rx="16" fill="#FFF9F1" stroke="#2F728E" stroke-width="3"/>
        <path d="M61 60H111" stroke="#2F728E" stroke-width="4" stroke-linecap="round"/>
        <path d="M61 76H96" stroke="#2F728E" stroke-opacity="0.6" stroke-width="4" stroke-linecap="round"/>
        <circle cx="208" cy="73" r="34" fill="#E8F1F4"/>
        <path d="M192 73L202 83L225 59" stroke="#F2B36D" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M133 69H174" stroke="#163242" stroke-opacity="0.2" stroke-width="4" stroke-linecap="round" stroke-dasharray="6 8"/>
      </svg>
    `,
    intake: `
      <svg viewBox="0 0 320 150" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
        <rect x="62" y="52" width="150" height="52" rx="12" fill="#2F728E" fill-opacity="0.12" stroke="#2F728E" stroke-width="3"/>
        <rect x="94" y="40" width="124" height="16" rx="8" fill="#F2B36D" fill-opacity="0.65"/>
        <path d="M62 112H258" stroke="#163242" stroke-opacity="0.18" stroke-width="4" stroke-linecap="round"/>
        <circle cx="92" cy="112" r="10" fill="#163242"/>
        <circle cx="176" cy="112" r="10" fill="#163242"/>
        <path d="M224 44L258 44" stroke="#163242" stroke-width="4" stroke-linecap="round"/>
        <path d="M224 60L274 60" stroke="#163242" stroke-opacity="0.4" stroke-width="4" stroke-linecap="round"/>
      </svg>
    `,
    weighing: `
      <svg viewBox="0 0 320 150" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
        <path d="M50 111H270" stroke="#163242" stroke-opacity="0.18" stroke-width="4" stroke-linecap="round"/>
        <rect x="68" y="76" width="136" height="22" rx="11" fill="#163242" fill-opacity="0.08" stroke="#163242" stroke-opacity="0.22" stroke-width="3"/>
        <rect x="84" y="48" width="104" height="30" rx="10" fill="#2F728E" fill-opacity="0.14" stroke="#2F728E" stroke-width="3"/>
        <path d="M132 48V22" stroke="#2F728E" stroke-width="4" stroke-linecap="round"/>
        <circle cx="132" cy="20" r="12" fill="#F2B36D" fill-opacity="0.72"/>
        <path d="M222 33C242.987 33 260 50.0132 260 71C260 91.9868 242.987 109 222 109C201.013 109 184 91.9868 184 71C184 50.0132 201.013 33 222 33Z" fill="#FFF9F1" stroke="#2F728E" stroke-width="3"/>
        <path d="M222 48V71L238 80" stroke="#F2B36D" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    `,
    purchase: `
      <svg viewBox="0 0 320 150" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
        <rect x="58" y="38" width="92" height="74" rx="18" fill="#FFF9F1" stroke="#F2B36D" stroke-width="3"/>
        <path d="M82 61H126" stroke="#163242" stroke-opacity="0.8" stroke-width="4" stroke-linecap="round"/>
        <path d="M82 78H118" stroke="#163242" stroke-opacity="0.35" stroke-width="4" stroke-linecap="round"/>
        <path d="M194 44H254C262.837 44 270 51.1634 270 60V90C270 98.8366 262.837 106 254 106H194C185.163 106 178 98.8366 178 90V60C178 51.1634 185.163 44 194 44Z" fill="#2F728E" fill-opacity="0.12" stroke="#2F728E" stroke-width="3"/>
        <path d="M208 62H240" stroke="#2F728E" stroke-width="4" stroke-linecap="round"/>
        <path d="M208 78H228" stroke="#2F728E" stroke-opacity="0.5" stroke-width="4" stroke-linecap="round"/>
        <circle cx="168" cy="75" r="12" fill="#F2B36D"/>
        <path d="M150 75H112" stroke="#163242" stroke-opacity="0.2" stroke-width="4" stroke-linecap="round" stroke-dasharray="6 8"/>
      </svg>
    `,
    issue: `
      <svg viewBox="0 0 320 150" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
        <path d="M48 112H272" stroke="#163242" stroke-opacity="0.18" stroke-width="4" stroke-linecap="round"/>
        <path d="M84 95H170C181.046 95 190 86.0457 190 75V67C190 55.9543 181.046 47 170 47H114" stroke="#2F728E" stroke-width="4" stroke-linecap="round"/>
        <path d="M112 33L88 47L112 61" stroke="#2F728E" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
        <rect x="202" y="40" width="72" height="70" rx="18" fill="#FFF9F1" stroke="#F2B36D" stroke-width="3"/>
        <path d="M221 69L235 83L256 57" stroke="#2A8C68" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    `
  };

  return sketches[type] || sketches.booking;
}

function renderTruckSvg() {
  return `
    <svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
      <rect x="8" y="22" width="28" height="16" rx="4" fill="#2F728E"/>
      <path d="M36 26H46L54 34V38H36V26Z" fill="#F2B36D"/>
      <circle cx="20" cy="42" r="5" fill="#163242"/>
      <circle cx="46" cy="42" r="5" fill="#163242"/>
      <path d="M12 18H34" stroke="#163242" stroke-width="3" stroke-linecap="round"/>
    </svg>
  `;
}

function firstElement(root, selector) {
  const node = root.querySelector(selector);
  if (!node) {
    throw new Error(`Missing element for selector: ${selector}`);
  }
  return node;
}

function setText(root, selector, value) {
  firstElement(root, selector).textContent = value;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function isAnswerCorrect(step, selectedAnswers) {
  if (!step.quiz) {
    return false;
  }

  const selected = Array.isArray(selectedAnswers) ? selectedAnswers : [];
  const expected = new Set(step.quiz.correctAnswers || []);

  if (step.quiz.selectionMode === "single") {
    return selected.length === 1 && expected.has(selected[0]);
  }

  const selectedSet = new Set(selected);
  return selectedSet.size === expected.size && [...selectedSet].every((answer) => expected.has(answer));
}

function launchConfetti(container) {
  const existing = document.querySelector(".confetti-layer");
  if (existing) {
    existing.remove();
  }

  const layer = document.createElement("div");
  layer.className = "confetti-layer";
  layer.setAttribute("aria-hidden", "true");

  const rect = container.getBoundingClientRect();
  const originX = window.innerWidth * 0.5;
  const originY = Math.max(84, rect.top + Math.min(56, rect.height * 0.18));

  const colors = ["#0b415f", "#2f728e", "#276c6f", "#369599", "#b7791f", "#d467d1", "#8bc2d8"];
  const pieceCount = 160;

  for (let i = 0; i < pieceCount; i += 1) {
    const piece = document.createElement("span");
    piece.className = "confetti-piece";

    const dx = Math.round((Math.random() * 2 - 1) * 640);
    const dy = Math.round(260 + Math.random() * 520);
    const rot = Math.round((Math.random() * 2 - 1) * 840);
    const wave = i % 2;
    const delay = (wave * 0.14 + Math.random() * 0.28).toFixed(3);
    const duration = (2.4 + Math.random() * 1.4).toFixed(2);
    const size = 8 + Math.round(Math.random() * 10);
    const hue = colors[i % colors.length];
    const offsetX = (Math.random() * 140 - 70).toFixed(2);
    const offsetY = (Math.random() * 40 - 20).toFixed(2);

    piece.style.setProperty("--dx", `${dx}px`);
    piece.style.setProperty("--dy", `${dy}px`);
    piece.style.setProperty("--rot", `${rot}deg`);
    piece.style.setProperty("--delay", `${delay}s`);
    piece.style.setProperty("--dur", `${duration}s`);
    piece.style.setProperty("--size", `${size}px`);
    piece.style.setProperty("--color", hue);
    piece.style.left = `${originX + Number(offsetX)}px`;
    piece.style.top = `${originY + Number(offsetY)}px`;

    layer.append(piece);
  }

  document.body.append(layer);
  setTimeout(() => layer.remove(), 4200);
}